version: 0.2
phases:
  install:
    runtime-versions:
      node-js: 16
    commands:
      - echo Getting Started
  pre_build:
    commands:
      - echo installing source npm dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the codes
      - npm run build
      - echo build finished, now moving to s3
  post_build:
    commands:
      - echo build completed on `date`
      - aws s3 sync build/ s3://react-quiz-app-codebuild-mar-16 --acl public-read